export const GET_REQUEST_STARTED="GET_REQUEST_STARTED";
export const GET_REQUEST_SUCCEEDED="GET_REQUEST_SUCCEEDED";
export const GET_REQUEST_FAILED="GET_REQUEST_FAILED";
export const CREATE_REQUEST_STARTED="CREATE_REQUEST_STARTED";
export const CREATE_REQUEST_SUCCEEDED="CREATE_REQUEST_SUCCEEDED";
export const CREATE_REQUEST_FAILED="CREATE_REQUEST_STARTED";