import {
  Box,
  chakra,
  Flex,
  Grid,
  GridItem, Img,
  Show
} from "@chakra-ui/react";
import Head from "next/head";
import Image from 'next/image'
// import Image from "next/image";
// import OnboardingImage from '../../../public/assets/svgs/OnboardingImage.svg'


interface AuthLayoutProps {
  children: any;
  title: string
}

const AuthLayout = ({ children, title }: AuthLayoutProps) => {
  const OnboardingImage = 'https://switcha-production.fra1.cdn.digitaloceanspaces.com/web-app/assets/images/OnboardingImage.jpg'
  return (
    <Flex flexDirection={'column'} align="stretch" minH="100vh" h="100vh" bg="mainBGColor" w="full" overflowX={'hidden'}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/svgs/logo-single.svg" />
      </Head>
      <chakra.header id="header">
        <Flex w="100%" bg="appDarkColor" px="8" py={{ md: "4", base: '2' }}>
          <Img src="/assets/svgs/Logo.svg" alt="" w={'32'} />
        </Flex>
      </chakra.header>
      <Flex alignItems={'center'} justifyContent={'center'} h={'full'} overflow={'scroll'}>
        <Grid templateColumns={{ md: "repeat(2, 1fr)", base: '1fr' }} gap={{ md: '16', base: '1' }} h="full" >
          <Show above='md'>
            <GridItem w="100%" h="full">
              <Flex justifyContent="center" h="full" alignItems="center">

                <Box p="4" boxSize={{ lg: "lg", md: 'xs', base: 'xs' }} position={'relative'}>
                  {/* <Image src={'/assets/svgs/OnboardingImage.svg'} alt='' layout="fill" objectFit="fill" priority />
                   */}
                  <Image src={OnboardingImage} alt='Auth Image' layout="fill" objectFit="fill" priority />
                  {/* <Img
                    src="/assets/svgs/OnboardingImage.svg"
                    alt=""
                    objectFit="cover"
                    boxSize={{ lg: "lg", md: 'xs', base: 'xs' }}
                  /> */}
                </Box>


              </Flex>
            </GridItem>
          </Show>
          <GridItem w="100%" h="full" >
            <Flex justifyContent="center" h="full" alignItems="center" >
              {/* <Box p='4' bg='red.400'>
                            Box 1
                        </Box> */}
              {children}
            </Flex>
          </GridItem>
        </Grid>
      </Flex>

    </Flex>
  );
};

export default AuthLayout;
