import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Text } from "@chakra-ui/react";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import MainAppButton from "../components/buttons/MainAppButton";
import Settings from "./settingsui/Settings";
import Profile from "./settingsui/Profile";
import Verification from "./settingsui/Verification";
import Verfication2 from "./settingsui/Verfication2";
import Security from "./settingsui/Security";
import AccountActivity from "./settingsui/AccountActivity";
import AuthPage from "./settingsui/AuthPage";
const Home: NextPage = () => {
  return (
    <div>
      <ToastContainer
        position="top-right"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
      />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* test */}
      {/* <MainAppButton isLoading={false} >Submit</MainAppButton>
      <Text>hi</Text> */}
      <Settings />
      <Profile />
      <Verification />
      <Verfication2 />
      <Security />
      <AccountActivity />
      <AuthPage />
    </div>
  );
};

// Unable to apply fontSize prop to <MainAppButton/>

export default Home;
