
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ToastContainer, } from 'react-toastify';
<<<<<<< HEAD
import MainAppButton from '../components/buttons/MainAppButton';
import SignUpPage from './signup/index';
=======
import MainAppButton from '../components/buttons/MainAppButton'
import SignUpPage from './auth/SignUpPage';
>>>>>>> b9d3f7feb5882db28e2c042046f5b5ab909b0c58



const Home: NextPage = () => {
  return (
    <div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* test */}
      {/* <MainAppButton isLoading={false} >Submit</MainAppButton>
      <Text>hi</Text> */}
      {/* <Settings/> */}

      <SignUpPage />
      {/* <MainAppButton isLoading={false} >Submit</MainAppButton> */}

    </div>
  );
};

// Unable to apply fontSize prop to <MainAppButton/>

export default Home;
