export const SHOW_SWAP_SUCCESS_MODAL = "SHOW_SWAP_SUCCESS_MODAL";
export const SWAP_COIN_STARTED = "SWAP_COIN_STARTED";
export const SWAP_COIN_SUCCEEDED = "SWAP_COIN_SUCCEEDED";
export const SWAP_COIN_FAILED = "SWAP_COIN_FAILED";