name: Switcha Africa Frontend staging continuous integration

on:
  push:
    branches:
      - staging
    tags:
      - stage-*

env:
  REGISTRY: "registry.digitalocean.com/switcha-africa"
  REGISTRY_NAME: "switcha-africa"
  IMAGE_NAME: "switcha-staging-frontend-app"
  COMMAND: "npm run start"


jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download .env from url
      uses: suisei-cn/actions-download-file@v1
      id: downloadfile  # Remember to give an ID if you need the output
      with:
        url: "https://res.cloudinary.com/https-dynastys-org/raw/upload/v1655076813/switcha-staging-env/env_r2vems.txt"
        target: ./

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Get the commit hash
      id: tag
      run: echo ::set-output name=IMG_TAG::$(echo $GITHUB_SHA)

    - name: Build and tag the Docker image
      run: docker build ./ --file ./Dockerfile
        --tag registry.digitalocean.com/switcha-africa/switcha-staging-frontend-app:latest

    - name: Push the tagged Docker image
      run: |
        docker push registry.digitalocean.com/switcha-africa/switcha-staging-frontend-app:latest

    - name: Deploy to Digital Ocean droplet via SSH action
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        envs: ${{secrets.IMAGE_NAME}},${{ secrets.CONTAINER_REGISTRY_NAME }},${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }},GITHUB_SHA
        script: |
            # docker image
            docker rmi -f registry.digitalocean.com/switcha-africa/switcha-staging-frontend-app:latest

            # pull latest image
            docker pull registry.digitalocean.com/switcha-africa/switcha-staging-frontend-app:latest
            
            # Run a new container from a new image
            docker run -d --restart always --publish 3000:3000 registry.digitalocean.com/switcha-africa/switcha-staging-frontend-app:latest

