name: Switcha Africa Exchange Staging continuous integration

on:
  push:
    branches:
      - staging-v2
    tags:
      - staging-v2-stage-*

env:
  REGISTRY: "registry.digitalocean.com/switcha-africa"
  REGISTRY_NAME: "switcha-africa"
  IMAGE_NAME: "switcha-staging-exchange-page"
  COMMAND: "npm run start"
  NEXT_PUBLIC_NODE_ENV: "staging"
  NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.API_ENDPOINT_STAGING }}


jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download .env from url
      uses: suisei-cn/actions-download-file@v1
      id: downloadfile  # Remember to give an ID if you need the output
      with:
        url: "https://res.cloudinary.com/https-dynastys-org/raw/upload/v1655076813/switcha-staging-env/env_r2vems.txt"
        target: ./

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Get the commit hash
      id: tag
      run: echo ::set-output name=IMG_TAG::$(echo $GITHUB_SHA)

    - name: Build and tag the Docker image
      run: docker build --rm ./ --file ./Dockerfile
        --tag registry.digitalocean.com/switcha-africa/${{secrets.SWITCHA_STAGING_EXCHANGE_NAME_IMAGE_NAME}}:latest

    - name: Push the tagged Docker image
      run: |
        docker push registry.digitalocean.com/switcha-africa/${{secrets.SWITCHA_STAGING_EXCHANGE_NAME_IMAGE_NAME}}:latest

    - name: Deploy to Digital Ocean droplet via SSH action
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        envs: ${{secrets.SWITCHA_STAGING_EXCHANGE_NAME_IMAGE_NAME}},${{ secrets.REGISTRY_NAME }},${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }},GITHUB_SHA
        script: |
            #docker stop container 
            docker stop ${{secrets.SWITCHA_STAGING_EXCHANGE_NAME_IMAGE_NAME}} 

            # rm
            docker rm -f ${{secrets.SWITCHA_STAGING_EXCHANGE_NAME_IMAGE_NAME}}

            # deleting untagged image
            #docker rmi $(docker images --filter "dangling=true" -q --no-trunc)

            # pull latest image
            docker pull registry.digitalocean.com/switcha-africa/${{secrets.SWITCHA_STAGING_EXCHANGE_NAME_IMAGE_NAME}}:latest

            # Run a new container from a new image
            docker run --name ${{secrets.SWITCHA_STAGING_EXCHANGE_NAME_IMAGE_NAME}} -d --restart always --publish 4000:4000 registry.digitalocean.com/switcha-africa/${{secrets.SWITCHA_STAGING_EXCHANGE_NAME_IMAGE_NAME}}:latest

            # deleting untagged image
            #docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
